разметка главной
aendnn/project pull request #3
Opened 2022-05-23 15:37 UTC by holyflameq

2022-05-25 00:43 UTC, holyflameq commented
там и индекс. и каталог

2022-05-25 17:16 UTC, aendnn requested changes

2022-05-25 17:16 UTC, aendnn commented on index.html
> +  <title>Интернет-магазин мороженого «Glacy Shop»</title>
неправильно указано название магазина

2022-05-25 17:16 UTC, aendnn commented on index.html
> +<div>
установи в атоме плагин atom-beautify для правильного форматирования, чтобы соблюдать правильную вложенность тегов
либо вручную каждый дочерний тег отбиваq табом в редакторе, тогда получится правильная иерархия

2022-05-25 17:16 UTC, aendnn commented on index.html
> +      <img src="img/index-logo.svg" width="154" height="64" alt="Логотип интернет-магазина мороженого «Glacy Shop»">
название магазина в alt исправь тоже)

2022-05-25 17:16 UTC, aendnn commented on index.html
> +      <h4>Новинки</h4>
вот здесь грубая ошибка валидации, в список можно вложить ТОЛЬКО элементы списка.
в элементы списка уже можно вкладывать всё, что угодно. в сам список - только li.
тут валидатор показывает error, исправь
и + мне кажется, "новинки" может быть ссылкой на полноценную страницу с новинками всех мороженок

2022-05-25 17:16 UTC, aendnn commented on index.html
> +      <li>
в элементах явно должна быть ссылка 
upd: + в тз указано, что элемент "сливочное" должен вести на страницу каталога

2022-05-25 17:16 UTC, aendnn commented on index.html
> +      <ul>
подсписок и заголовок или ссылка, как я написала ниже, нужно обернуть в общий блок для будущей стилизации

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <section>
добавить общий блок для поиска, входа и корзины. это нужно и для стилизации, и логически это такой user navigation

2022-05-25 17:16 UTC, aendnn commented on index.html
> +        <button type="button">Закрыть</button>
судя по макету главной, если в корзине пусто, то клик по ней - переход на полноценную страницу с корзиной
если есть товары - по наведению появляется попап, его нужно разметить в этом же блоке

2022-05-25 17:16 UTC, aendnn commented on index.html
> +        <button type="button">Закрыть</button>
возможно, это просто заглушка, но почему "закрыть"?

2022-05-25 17:16 UTC, aendnn commented on index.html
> +        <button type="button">Закрыть</button>
и тут тоже, эта кнопка не просто закрывает форму

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <p><b>с 10 до 20, ежедневно</b><br>
график работы и номер телефона обернуть в общий блок, это я точно говорила)
и я считаю его нужно вынести за пределы nav, потому что это НЕ главная навигация по сайту
br тут лишний, так как p - блочный элемент, он и так не допустит рядом никаких элементов

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <a href="tel:+79001111111">8-812-450-25-25</a>
href правильный, но номер телефона не соответствует

2022-05-25 17:16 UTC, aendnn commented on index.html
> +<main>
должен быть главный заголовок страницы, даже если его нет в макете

2022-05-25 17:16 UTC, aendnn commented on index.html
> +        <img src="img/studio.jpg" alt="Крем-Брюле">
мы с тобой говорили про figure и figcaption, почему решил так сделать?

2022-05-25 17:16 UTC, aendnn commented on index.html
> +  <section>
необязательно, но желательно в секции добавлять подзаголовок

2022-05-25 17:16 UTC, aendnn commented on index.html
> +      <img src="img/Malinka.jpg" alt="Малинка даром!">
мы обсуждали, что это фон, а не контентное изображение

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <h2>Шоколадки даром!</h2>
слишком крупный заголовок, считаю что для общей секции логичнее будет сделать крупный заголовок, которй описывает, что внутри (спецпредложения, например)
а эти заголовки сделать поменьше

2022-05-25 17:16 UTC, aendnn commented on index.html
> +           <h4>Сливочное с апельсиновым <br>джемом и цитрусовой стружкой</h4>
после h2 следующий по важности h3

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <p><a href="blog.html"><b>10 способов сервировки <br>фруктовых щербетов <br>к столу</b></a></p>
это мы тоже обсуждали. нужен общий див для этих блоков

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <p><a href="blog.html"><b>10 способов сервировки <br>фруктовых щербетов <br>к столу</b></a></p>
если не считаешь это заголовком - убери абзац. оставь ссылку и b

2022-05-25 17:16 UTC, aendnn commented on index.html
> +  <section>
нужен подзаголовок

2022-05-25 17:16 UTC, aendnn commented on index.html
> +          <input type="email" name="email" id="email"  placeholder="email@example.com">
нет скрытого лейбла

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <button type="submit" value="Отправить"></button>
Отправить нужно писать в самом теге, value убрать - старый синтаксис

2022-05-25 17:16 UTC, aendnn commented on index.html
> +      <h2>Контактная информация</h2>
логичнее вынести этот заголовок в общую с картой секцию

2022-05-25 17:16 UTC, aendnn commented on index.html
> +        <a href="tel:+79001111111"><b>8-812-450-25-25</b></a><br>
номер поменять

2022-05-25 17:16 UTC, aendnn commented on index.html
> +       <p>Как до нас добраться</p>
лучше сделать общий заголовок для карты и контактной информации

2022-05-25 17:16 UTC, aendnn commented on index.html
> +          <li>
для дальнейшей стилизации нужно разместить элементы списка в ряд.
наши документы - 2 элемент, о производстве - 3

2022-05-25 17:16 UTC, aendnn commented on index.html
> +   </p>
нет копирайта

2022-05-25 17:16 UTC, aendnn commented on index.html
> +             <span>Хит!</span>
по критерию Д2 (доп. критерии, для перфекционостов :)), этот span лучше убрать и сделать хит через класс псевдоэлементом

2022-05-25 17:16 UTC, aendnn commented on index.html
> +    <p>
ТЗ
[3.7.] Логотип Академии и ссылка HTML Academy в подвале ведут на [лендинг интенсива «HTML и CSS. Профессиональная вёрстка сайтов»](https://htmlacademy.ru/intensive/htmlcss).

2022-05-25 17:16 UTC, aendnn commented on index.html
> +      <li><a href="product.html">
ТЗ
[3.12.] Карточка товара: поведение этого элемента при наведении на главной странице аналогичны поведению на странице каталога (смотрите страницу styleguide).

добавь ссылку быстрый просмотр после названия мороженки

ссылка потому что я не вижу в макете попапа с продуктов, думаю предполагалось, что должна быть отдельная страница с продуктом

2022-05-25 19:54 UTC, aendnn requested changes

2022-05-25 19:54 UTC, aendnn commented on catalog.html
> +  <title>Каталог — Магазина мороженого «Glacy Shop»</title>
тут тоже исправить название

2022-05-25 19:54 UTC, aendnn commented on catalog.html
> +        <a>
добавить href на главную, так как это внутренняя страница

2022-05-25 19:54 UTC, aendnn commented on catalog.html
> +          <a href="catalog.html">Магазин</a>
в макете тут каталог, а не магазин)

2022-05-25 19:54 UTC, aendnn commented on catalog.html
> +        <h2>Список сливочного мороженого</h2>
в заголовке не должно быть слова список, формируй заголовки так как их гуглил бы пользователь

2022-05-25 19:54 UTC, aendnn commented on catalog.html
> +              <button>Быстрый просмотр</button>
насчет кнопки/ссылки писала на главной, не вижу попапа. нужно обсудить, как ты это видишь

2022-05-25 19:54 UTC, aendnn commented on catalog.html
> +            <button type="button">></button>
здесь тоже должна быть ссылка, там логика на бэке одинаковая для всех элементов, нужна ссылка

2022-05-27 23:01 UTC, aendnn requested changes
🥲

2022-05-27 23:04 UTC, aendnn requested changes
🥲

2022-05-27 23:12 UTC, aendnn requested changes

2022-05-27 23:12 UTC, aendnn commented on index.html
> +          <h2>Магазин мороженого Глэйси</h2>
Зачем он тут?)

2022-05-27 23:12 UTC, aendnn commented on index.html
> +              <h2>Когда есть товары</h2>
Тут логика другая, товары либо есть либо их нет. По макету на главной пустая корзина, в каталоге 2 товара. Так и сделай)

2022-05-27 23:12 UTC, aendnn commented on index.html
> +                    Пломбир с апельсиновым джемом
Мы обсуждали, что это что?)

2022-05-27 23:12 UTC, aendnn commented on index.html
> +        <h2>ЕБЕЙШИЕ ПРЕДОЖЕНИЯ!</h2>
😍

2022-05-27 23:12 UTC, aendnn commented on index.html
> +          <p>
Не закрыл предыдущий абзац, открыл новый

2022-05-27 23:12 UTC, aendnn commented on catalog.html
> +              <h4>Сливочное с апельсиновым <br>джемом и цитрусовой стружкой</h4>
На главной h3, тут h4. Блоки идентичные

2022-05-28 00:56 UTC, merged