Сделал  подписи классов. В index.html
aendnn/project pull request #5
Opened 2022-05-31 13:59 UTC by holyflameq

2022-05-31 15:47 UTC, aendnn requested changes

2022-05-31 15:47 UTC, aendnn commented on index.html
> +              <ul class="product-navigation">
здесь product не подойдет, так как product - это товар, у тебя же здесь подменю каталога

2022-05-31 15:47 UTC, aendnn commented on index.html
> +            <li class="site-navigation-item"><a href="catalog.html">Каталог</a>
для стилизации нужно будет обращаться к ссылке, почему ты не задал ей класс? будет вложенность .site-navigation-item a?

2022-05-31 15:47 UTC, aendnn commented on index.html
> +                  <a class="button-product" href="product.html">
это разве button?) нежелательно привязывать типы тегов к названиям классов, потому что тег может измениться

2022-05-31 15:47 UTC, aendnn commented on index.html
> +        <section class="popap-header">
popUp - это всплывающее окно, сам блок который показывается/скрывается, не нужно весь родительский блок именовать как попап.
у секшна должно быть название описывающее в целом, ЧТО ЭТО. у тебя это что?)

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <div class="popap-header-search">
я вообще против указания местоположения тега (header/main/footer), потому что поиск может так же появиться в футере, например. тогда тебе нужно будет менять полностью класс и все стили вешать на popap-footer-search, а это дублирование кода = замедление загрузки страницы

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <div class="popap-header-search">
должно быть глобальное название, это не попап. попап то, что выпадает. у тебя пока этого блока в разметке нет (форма поиска).

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <div class="popap-header-login">
здесь и дальше сделать по аналогии с поиском

2022-05-31 15:47 UTC, aendnn commented on index.html
> +            <button сlass="login-link" type="submit">Войти</button>
здесь нужно переписать форму логина, потому что тут кнопка, а в классе указана ссылка. вернемся к этому после разметки всплывающих форм

2022-05-31 15:47 UTC, aendnn commented on index.html
> +    <main class="container">
зачем здесь класс контейнер?)

2022-05-31 15:47 UTC, aendnn commented on index.html
> +      <section class="big-features">
это не преимущества(

2022-05-31 15:47 UTC, aendnn commented on index.html
> +        <ul class="big-features-page">
page??? почему так? это же список-слайдер

2022-05-31 15:47 UTC, aendnn commented on index.html
> +            <a class="button" href="Catalog.html">
тег ссылки, зачем ты именуешь как кнопку?) здесь просто переход, тут нет оформления

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <li class="big-features-item1">
у этих элементов будет одинаковая стилизация, если оставить такой класс, тебе нужно будет дублировать .big-features-item1, big-features-item2, big-features-item3, это плохой подход. 
нужно для идентичных элементов делать одинаковые классы, если какой-то из элементов требует доп. стилизации или функционала - добавляешь ему индивидуальный класс

2022-05-31 15:47 UTC, aendnn commented on index.html
> +              <figure class="big-features-item1-image">
здесь то же самое: один класс для идентичных элементов, потому что стилизация будет одинаковая

2022-05-31 15:47 UTC, aendnn commented on index.html
> +              <figure class="big-features-item1-image">
это не совсем image, image - картинка внутри, которой ты не задал класс
здесь содержимое слайда, блок-обертка. 
думаю, тут будет уместно слово content

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <li><button class="slider" type="button">Кнопка переключения слайдера</button></li>
slider - слишком глобальный класс, он больше подходит для секции, в которой эти переключалки находятся

2022-05-31 15:47 UTC, aendnn commented on index.html
> +      <section class="medium-features">
на странице обычно больше 1 блока с преимуществами не бывает. тут тоже не преимущества( советую переводить заголовки в переводчике, так будет проще именовать секции поначалу

2022-05-31 15:47 UTC, aendnn commented on index.html
> +        <div class="medium-features-item1">
про item1/item2 писала выше

2022-05-31 15:47 UTC, aendnn commented on index.html
> +            <a class="button" href="catalog.html">Хочу варенье!</a> <!-- Мне кажется тут кнопка а не ссылка. Кнопка типа <button type="submit">Хочу варенье!</button> -->
ссылке нужно добавить доп. класс для позиционирования

2022-05-31 15:47 UTC, aendnn commented on index.html
> +                <p class="catalog-hit-text-price"><b>310 ₽</b>/кг</p>
text лишнее

2022-05-31 15:47 UTC, aendnn commented on index.html
> +              <div class="catalog-hit-image">
у тебя выше нет каталога, только hits. для единообразия, сделай в одном стиле: hit-image/ hit-item-image

2022-05-31 15:47 UTC, aendnn commented on index.html
>              <button type="button">Быстрый просмотр</button>
доп.класс для стилизации и позиционирования нужен

2022-05-31 15:47 UTC, aendnn commented on index.html
> +      <section class="advantages">
здесь всё идеально, молодец! и лист и айтем, всё супер. 
этот блок - это те самые features, которых у тебя аж 2 штуки выше)

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <a class="blog-text" href="blog.html"><b>10 способов сервировки <br>фруктовых щербетов <br>к столу</b></a>
я считаю, что это заголовок статьи, а ты?)

2022-05-31 15:47 UTC, aendnn commented on index.html
> +        <section class="news-letter">
тут не нужен дефис

2022-05-31 15:47 UTC, aendnn commented on index.html
>            <form action="https://Glacy" method="post">
почему у формы нет класса? и во внутреннем диве он неправильный, это обертка

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <p class="contacts-text-adress">
обозначение text лишнее

2022-05-31 15:47 UTC, aendnn commented on index.html
> +    <footer class="page-footer main-footer">
а зачем тут 2 класса?) ответ: "так в демке" не принимается

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <li class="footer-social-item-f">
про идентичные элементы писала выше

2022-05-31 15:47 UTC, aendnn commented on index.html
> +          <li class="footer-contacts-item-left">
здесь идентичные элементы, некоторые из них отличаются, значит нужен доп. класс
позиционирование тут ставится автоматом, указывать какой где элемент не требуется

2022-05-31 18:50 UTC, aendnn requested changes

2022-05-31 18:50 UTC, aendnn commented on index.html
> +              <figure class="big-offers-item-slide-content">
слишком длинный получился класс, поменяй как обсуждали в тг

2022-05-31 18:50 UTC, aendnn commented on index.html
> +              <div class="hits-item-image">
здесь не только image, еще и прайс

2022-05-31 18:50 UTC, aendnn commented on index.html
> +          <li class="footer-contacts-item footer-contacts-item-left">
доп. классы лишние, можешь оставить конечно, но ты поймешь потом, что по ним не будет никакой стилизации)

2022-05-31 18:50 UTC, aendnn commented on index.html
> +        <a class="button footer-copyright-link" href="https://htmlacademy.ru/intensive/htmlcss">
ты сделал по аналогии с барбершопом, но в нем присутствует класc button потому что в макете ссылка сделана как кнопка, как все кнопки в том макете. у тебя же просто ссылка, внутри которой лого и все

2022-05-31 20:18 UTC, aendnn requested changes

2022-05-31 20:18 UTC, aendnn commented on catalog.html
> +                  <td class="cart-item-price-count">
count где кол-во и стоимость

2022-06-06 21:30 UTC, aendnn requested changes
правки

2022-06-06 22:00 UTC, aendnn requested changes

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +    /* Chrome 26+, Opera 23+, Firefox 39+ */
Подключать шрифты нужно учиться самостоятельно

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +/* roboto-500 - latin */
Для русского текста нужна кириллица

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +  --brown-light: #9D8B84;
Правильнее оттенок задавать перед цветом, как ты сделал с dark чуть выше

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +  margin: 0px;
Если у тебя подключён нормалайз, то обнуление для body уже прописано, дублировать не нужно

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +  font-family: 'Roboto';
Нужно прописать запасной шрифт на случай если твой не подключится. + если даже запасного нет - прописать какой шрифт нужно подключить serif(с засечками) или sans-serif(без засечек), смотря какой у тебя основной шрифт (с засечками или без)

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +  background-repeat: no-repeat;
Фон повторяется только если есть фоновое изображение, у тебя только фортовый цвет

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +}
Обычно в body прописываются ещё размер шрифта и высота строки основного текста, чтобы не прописывать потом каждому абзацу размеры. посмотри по макету какой размер чаще всего повторяется и пропиши его тут

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +.site-navigation-list {
По умолчанию у списков есть отступы и внутренние и внешние, нужно обнулить margin, padding и прописать list-style-type: none. Должны попасть кружочки

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +  font: inherit;
В нормалайзе прописано ужр

2022-06-06 22:00 UTC, aendnn commented on css/style.css
> +  height: 229px;
не рекомендуется задавать высоту таким элементам, если текста станет больше, он вылезет за пределы блока, а он должен растягиваться по высоте, если текста становится больше

2022-06-07 09:31 UTC, aendnn requested changes

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +.advantages h3 {
Нет класса для заголовка? Почему тег стилизуешь?

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +
Почему не по классу?)

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +  border-bottom: 1px solid rgba(255, 255, 255, 0.2);
Тут нужно чтобы ты скинул скрин с макета и скрин того, что у тебя получилось

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +.footer-copyright p {
Здесь нет класса? Это не ошибки, где стилизация по тегу, мне просто интересно почему так, ты же вроде как давал каждому элементу класс

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +  border-bottom: 1px solid rgba(255, 255, 255, 0.2);
Тут нужно чтобы ты скинул скрин с макета и скрин того, что у тебя получилось

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +.page-body {
У тебя класс page-body и у каталога и у главной. Ты в самом начале стилизовал уже этот класс, эти стили применятся ко всем элементам, у которых есть этот класс, так что дублировать те же стили не нужно

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +  mid-width: 1200px;
Мид :)

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +  font: inherit;
Необязательно дублировать так как есть в нормалайзе

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +.site-navigation-item {
Лучше стили для меню вынести в начало файла, после стилей хедера, например. Потому что они относятся ко всем страницам сайта, не только к каталогу

2022-06-07 09:31 UTC, aendnn commented on css/style.css
> +  list-style: none;
Везде где есть списки, сделать как я писала выше

2022-06-08 06:32 UTC, aendnn requested changes

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +  font-family: 'Roboto', 'Arial', sans-serif;
Ну какой ты умничка 😍

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +  mid-width: 1200px;
мид опять)

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +  margin: 0px;
если значение 0, то можно убрать px

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +.page-body a {
Класс бади лишний, у тебя на каждой странице он, можно просто глобально задать тегу а стилизацию. В критерии Д25 есть исключения для бади, а и имг

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +h1 {
не пройдёшь по критерию Д25,это глобальный тег и он не разрешён(

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +.footer-social-list {
Можно задать эти стили для всех списков в футере, чтобы не дублировать одни и те же стили для разных классов

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +  text-decoration: underline;
Ты спрашивал почему у тебя не такая граница, как в макете. Потому что так работает подчёркивание, вместо него нужно задать бордер

2022-06-08 06:32 UTC, aendnn commented on css/style.css
> +.site-navigation-item {
Лучше стили для меню и его элементов  вынести в начало файла, после стилей хедера, например. Потому что они относятся ко всем страницам сайта, не только к каталогу

2022-06-08 18:14 UTC, holyflameq commented on css/style.css
> +h1 {
удалил его нахуй) ахъааххаахахахах

2022-06-08 18:17 UTC, holyflameq commented on css/style.css
> +.footer-social-list {
не пон

2022-06-08 18:17 UTC, holyflameq commented on css/style.css
> +.site-navigation-item {
не пон

2022-06-11 21:22 UTC, aendnn requested changes
Все отлично, кроме того, что ты путаешь пока в каком месте прописывать элементы. 
Пару правил:
1. Все, что внутри хедера - прописываешь после глобальных тегов 
2. Состояния элементов должны быть рядом с самим элементом, не в конце файла 
3. Навигация и ее внутренние элементы должны быть в одном месте, нельзя перемещать элементы в разные места в коде, даже если тебе кажется, что это элемент другой страницы

2022-06-11 21:22 UTC, aendnn commented on css/style.css
> +  font-weight: 700;
В макете большинство текста жирный? И советую свойства для шрифта задавать рядышком, жирность/размер/высота линии. Так код будет аккуратнее

2022-06-11 21:22 UTC, aendnn commented on css/style.css
> +.site-navigation-list {
Этот список нужно перенести выше в коде, чем его айтемы. 
Сначала родитель - потом его потомки

2022-06-11 21:22 UTC, aendnn commented on css/style.css
> +.footer-social-list {
footer-social-list, 
footer-contacts-list одинаковые стили сброса. Почему бы не прописать .footer ul и обнулить 2 списка?)

2022-06-11 21:22 UTC, aendnn commented on css/style.css
> +.site-navigation-item {
почему у тебя сайт навигейшн почти в конце файла стилей?

2022-06-11 21:22 UTC, aendnn commented on css/style.css
> +.big-offers-link:hover {
Состояния элемента прописываются сразу после его стилизации. 
Чтобы не листать вниз весь код и не искать состояния, они должны быть рядом. 
Элемент -> ниже его состояния

2022-06-11 21:22 UTC, aendnn commented on css/style.css
> +.user-navigation-cart-link {
Это не элемент каталога, это элемент всего хедера.

2022-06-12 23:35 UTC, holyflameq commented on css/style.css
> +  font-weight: 700;
да жирный

2022-06-12 23:40 UTC, holyflameq commented on css/style.css
> +.user-navigation-cart-link {
Cмотри. Меня смутило. что эта ссылка. Именно когда 2 товара в корзине- только в каталоге.
для Индекса я задал другую ссылку с 0 товаров

2022-06-13 12:40 UTC, aendnn commented on css/style.css
> +.user-navigation-cart-link {
Это ссылка на полноценную корзину и там и там. По наведению - всплывашка с товарами, по клику - переход на полноценную страницу с корзиной, я так это вижу

2022-06-13 12:44 UTC, aendnn commented on css/style.css
> +.footer-social-list {
Не сделал, ок) твоё решение

2022-06-13 12:49 UTC, aendnn requested changes
Все отлично, графику с телефона проверить нереально, она останется на потом. В остальном все правильно, элементы по файлу правильно размещены и подписаны комментами, это хорошая практика, ты молодец 😽
Делай дальше блоки

2022-06-19 11:09 UTC, merged